# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: steam
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: 
    branches:
      -main
    paths:
      - '.github/workflows/steam.yml'
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Current configuration doesn't require a GitHub token
          token: NOT_NEEDED
          filename: steam.svg
          # Options
          user: onhaze
          template: classic
          base: ""
          config_timezone: Asia/Seoul
          plugin_steam: yes
          plugin_steam_achievements_limit: 2
          plugin_steam_games_limit: 4
          plugin_steam_playtime_threshold: 4
          plugin_steam_recent_games_limit: 2
          plugin_steam_sections: player, most-played, recently-played
          plugin_steam_user: onhaze
