name: WakaTime Gist Update

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update WakaTime Gist
        uses: anmol098/waka-box-go@v4
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: <d34983ed5e7ba7f5c33713488d464d2f>
          
          SHOW_OS: "False"
          SHOW_TIMEZONE: "False"
          SHOW_PROJECTS: "False"
          SHOW_COMMIT: "False"
          SHOW_EDITORS: "False"
          SHOW_SHORT_INFO: "True"
